#!/usr/bin/env bash

##############################################################################
##
##  Changelog creation script for use with Git Shell & Drone.io
##  Created by Funwayguy for QuickBlacklist
##
##############################################################################

# Create document for update notice
echo $ver_num > version.txt
echo "https://drone.io/github.com/Funwayguy/Quick-Blacklist/files" >> version.txt
git log -1 --pretty=format:"%B" >> version.txt